#my_string = input('My name is Mohinur')
print('My name is Mohinur'.upper())
print('My name is Mohinur'.lower())
print('My name is Mohinur'.replace(' ',''))
print('My name is Mohinur'.replace('My name is Mohinur','M'))
print('My name is Mohinur'.replace('My name is Mohinur','r'))
